apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: maems_user
    secureJsonData:
      password: maems_password
    jsonData:
      database: maems_energy
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
